# Stochastic Gradient Descent (SGD) for Matrix Factorization

In [2]:
#### SGD in partially-observed case

import numpy as np

# Define the matrix A (example)
A = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])

# Parameters
num_users, num_items = A.shape
k = 2  # Number of latent features
alpha = 0.01  # Learning rate
num_iterations = 5000  # Number of iterations
lambda_reg = 0.02  # Regularization parameter

# Initialize W and H with random values
W = np.random.rand(num_users, k)
H = np.random.rand(num_items, k)
Wi = W.copy()
Hi = H.copy()

# SGD for Matrix Factorization
for iteration in range(num_iterations):
    for i in range(num_users):
        for j in range(num_items):
            if A[i, j] > 0:  # Only consider observed entries
                error = A[i, j] - np.dot(W[i, :], H[j, :].T)
                for r in range(k):
                    W[i, r] += alpha * (2 * error * H[j, r] - lambda_reg * W[i, r])
                    H[j, r] += alpha * (2 * error * W[i, r] - lambda_reg * H[j, r])

# Reconstructed matrix
A_pred = np.dot(W, H.T)
print("Original Matrix:\n", A)
print("Reconstructed Matrix:\n", A_pred)

Original Matrix:
 [[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
Reconstructed Matrix:
 [[4.9767976  2.98320845 2.01359298 1.00133435]
 [3.9815885  2.40319818 1.84949941 0.99957084]
 [1.00084369 0.99763568 6.14081362 4.97332361]
 [0.99886778 0.91406345 4.95178578 3.98438127]
 [1.14472488 0.99977614 4.9860292  3.9931206 ]]


# Alternating Least Squares (ALS) for Matrix Factorization

In [5]:
#### ALS in partially-observed case

import numpy as np

# Define the matrix A (example)
A = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])

# Parameters
num_users, num_items = A.shape
k = 2  # Number of latent features
lambda_reg = 0.1  # Regularization parameter
num_iterations = 10  # Number of iterations

# Initialize W and H with random values
W = np.random.rand(num_users, k)
H = np.random.rand(num_items, k)

# ALS for Matrix Factorization
for iteration in range(num_iterations):
    # Fix H and solve for W
    for i in range(num_users):
        W[i, :] = np.linalg.solve(
            np.dot(H.T, H) + lambda_reg * np.eye(k),
            np.dot(H.T, A[i, :].T)
        ).T

    # Fix W and solve for H
    for j in range(num_items):
        H[j, :] = np.linalg.solve(
            np.dot(W.T, W) + lambda_reg * np.eye(k),
            np.dot(W.T, A[:, j])
        ).T

# Reconstructed matrix
A_pred = np.dot(W, H.T)
print("Original Matrix:\n", A)
print("Reconstructed Matrix:\n", A_pred)

Original Matrix:
 [[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
Reconstructed Matrix:
 [[ 5.10279107  1.89527059 -0.71400725  1.55716362]
 [ 3.41221941  1.27349095 -0.45128646  1.08687433]
 [ 1.54358278  1.04150338  1.78268283  3.95423636]
 [ 1.1722101   0.80095507  1.39659541  3.07748995]
 [-0.43918076  0.54504836  3.0845807   5.13456498]]
