# Singular Value Decomposition

In [1]:
import numpy as np

# Define the matrix A
A = np.array([
    [1, 0, 0, 0, 2],
    [0, 0, 3, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 4, 0, 0, 0]
])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Convert S to a diagonal matrix
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(S)

# Reconstruct the original matrix (optional)
A_reconstructed = np.dot(U, np.dot(Sigma, VT))

# Print the results
print("Original Matrix A:")
print(A)

print("\nMatrix U:")
print(U)

print("\nSingular Values (Sigma):")
print(Sigma)

print("\nMatrix VT:")
print(VT)

print("\nReconstructed Matrix A (from U, Sigma, VT):")
print(A_reconstructed)

Original Matrix A:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 4 0 0 0]]

Matrix U:
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]
 [-1.  0.  0.  0.]]

Singular Values (Sigma):
[[4.         0.         0.         0.         0.        ]
 [0.         3.         0.         0.         0.        ]
 [0.         0.         2.23606798 0.         0.        ]
 [0.         0.         0.         0.         0.        ]]

Matrix VT:
[[ 0.         -1.          0.          0.          0.        ]
 [-0.          0.          1.         -0.          0.        ]
 [ 0.4472136  -0.         -0.         -0.          0.89442719]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]

Reconstructed Matrix A (from U, Sigma, VT):
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]]
